# ----------------------- #
#      Main Configs       #
# ----------------------- #

#for test on localhost
#url: http://localhost:4000/
url: http://devsharing.com

permalink: /:year/:categories/:title/
paginate: 10          # Posts per page on the blog index
recent_posts: 10       # Posts in the sidebar Recent Posts section

titlecase: true       # Converts page and post titles to titlecase
prygments : true
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]
excerpt_separator : ""
